--JOINS

create table A(
				user_id int primary key,
				user_type varchar (30) not null,
				user_name varchar(30) not null,
				user_password int not null
				)


create table B(
				id int foreign key references A(user_id),
				full_name varchar (40) not null
				)

select distinct UPPER (ENAME  +'	 WORKING AS A 	'+ JOB + ' AND MY EMPLOYEE NO IS ' 
+ CAST(EMPNO AS VARCHAR (10)) + ' AND MY HIRE DATE IS ' + CAST( HIREDATE AS VARCHAR(10) ) + ' AND MY COMISSION IS ' 
+CAST( COMM AS VARCHAR (10)) + ' AND MY DEPARTMENT NO '+ CAST( D.DEPTNO AS VARCHAR (10)) + ' AND MY LOCATION IS ' +CAST( D.LOC AS VARCHAR (10)) )
from EMP e, DEPT d



SELECT DISTINCT *
FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
JOIN EMP E1 ON EMP.MGR=E1.EMPNO

CREATE VIEW EMPLOYEE_DETAILS
AS
SELECT DISTINCT
				 EMP.EMPNO [EMPLOYEE ID]
				,EMP.ENAME [EMPLOYEE NAME]
				,EMP.JOB [DESIGNATION]
				,DNAME [DEPARTMENT NAME]
				,E1.ENAME [MANAGER NAME]
				,LOC [BRANCH NAME]
				,EMP.HIREDATE [JOIN DATE]
				,EMP.SAL [EMPLOYEE SALARY]

FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
JOIN EMP E1 ON EMP.MGR=E1.EMPNO


SELECT * FROM EMPLOYEE_DETAILS


SELECT * FROM EMP







